name=input("enter your name")
age=int(input("enter your age"))
marks=float(input("enter your marks"))

print("welcom", name)
print("age=", age)
print("marks=", marks)
print(type(name))
print(type(age))
print(type(marks))