collection=set()
collection.add(1)
collection.add(2)
collection.add("Anish kr")
collection.add((2,3,))
print(collection)
print(type(collection))
print(len(collection))
collection.remove(2)
collection.clear()
